// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDehu44SPvz9Pfh2L-ZWidGn-R_ZRcs1iQ',
    appId: '1:847059894383:android:bddf8e93caa3fe46128d9a',
    messagingSenderId: '847059894383',
    projectId: 'my-sample-project-6cb36',
    storageBucket: 'my-sample-project-6cb36.appspot.com',
    authDomain: 'my-sample-project-6cb36.firebaseapp.com',
    measurementId: 'G-3MZM3FN95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehu44SPvz9Pfh2L-ZWidGn-R_ZRcs1iQ',
    appId: '1:847059894383:android:bddf8e93caa3fe46128d9a',
    messagingSenderId: '847059894383',
    projectId: 'my-sample-project-6cb36',
    storageBucket: 'my-sample-project-6cb36.appspot.com',
  );
}
