name: Build and upload to Firebase App Distribution

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.2'
        channel: 'stable'
    - name: Download Flutter Dependencies
      run: flutter pub get
    - name: Generate Android APK
      run: flutter build apk
    - name: Upload Artifact
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: app/build/app/outputs/flutter-apk/app-release.apk